baseURL = "https://rappy325.github.io/sjtufur_page/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "东川路800号荣毛社"
publishDir = "public"

[params]
description = "东川路800号荣毛社活动动态"

[permalinks]
announcements = "/announcements/:slug/"
